### ISSUE TITLE
[Feature] Incremental update for stg_iterable__user_history

### ISSUE THREAD

**Issue by justin-fundrise** [fivetran/dbt_iterable_source#37]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

Currently rebuild the `stg_iterable__user_history` table is recreated on each run. 
Since this table has full user history in it, with updated timestamps, it would be rather simple to make this an incremental model, that can run much quicker. 

### How would you implement this feature?

Update `stg_iterable__user_history` to become incremental. 

```
{{ config(
        materialized='incremental',
        unique_key=['_fivetran_user_id','updated_at'],
        incremental_strategy='insert_overwrite' if target.type in ('bigquery', 'spark', 'databricks') else 'delete+insert',
        partition_by={"field": "updated_at", "data_type": "date"} if target.type not in ('spark','databricks') else ['updated_at'],
        file_format='parquet',
        on_schema_change='fail'
    ) 
}}

with base as (

    select * 
    from {{ ref('stg_iterable__user_history_tmp') }}

    {% if is_incremental() %}
    where updated_at >= coalesce((select max(updated_at) from {{ this }} ), '2010-01-01')
    {% endif %}
),
```

### Describe alternatives you've considered

Could run on a larger warehouse, but that would just be more expensive. 

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for opening this FR and the corresponding PR!

I definitely understand the value that would come from making this staging model incremental. I do want to callout that this isn't something we have typically done for other staging models in our packages. Primarily because the addition of incremental models includes additional complexity and makes the model more error prone in the future. That being said, I understand that this staging model can be quite large and I would be open to exploring this enhancement further if this is something that would benefit all the users of this package.

I'm going to do some investigating on my end regarding the general size of this table for most users, but in the meantime I do have one quick question about your proposal. I see you are making the staging model (currently a table) incremental. However, there is still the upstream tmp model which is materialized as a view. Is this something that you feel counteracts the enhancement gained from the incremental, or is the view sufficient to keep as-is in your opinion?

**Comment by justin-fundrise** [comment]
I do not see any issues with the upstream tmp model `stg_iterable__user_history_tmp` since this model is just a `select *` there is no added complexity that would slow down a query on the model. 

When comparing this vs the events models I can see that both the tmp and stg models are views, allowing the models to run quickly there. 
Was the reason that views were not used for the user_history model due to a performance impact on the list user unnest models?

**Comment by fivetran-joemarkiewicz** [comment]
@justin-fundrise yeah I believe we opted to adjust the events tmp and staging models to be view in order for us to not store all the event records in a duplicative table since the volume of this table is quite large.

However, I don't entirely know if there was a specific reason we kept the user_history staging model as a table. This tmp=view and staging=table is the standard for our models across our packages. However, that may not be entirely necessary here. Are you running this model in your own dbt_project.yml? If so, would you be able to adjust the materialization of this model to be a view. Do you see any performance degradation? If not, this may be a sufficient alternative to making the model incremental.

Let me know your thoughts!

**Comment by fivetran-joemarkiewicz** [comment]
@justin-fundrise wanted to bump my above question. Were you able to see any success with adjusting the materialization of the `stg_iterable__user_history` to be a view?

If that was successful, we can explore adding that as the default materialization for this model in the package.

**Comment by justin-fundrise** [comment]
Haven't had a chance to test yet. Will update once I have the results. Thanks!

**Comment by fivetran-reneeli** [comment]
Hi @justin-fundrise ! I am working on some Iterable package updates this sprint. Let me know if you were able to test Joe's suggestion. If it works, I could see it being helpful for other customers as well!

**Comment by justin-fundrise** [comment]
Hi, just tested this with `stg_iterable__user_history` as a view. All tests are on XS snowflake warehouse. 
The Before times are averages of multiple runs over a few days. 
The after times are from just 1 run. 

We are not using the `iterable__events` model, so the performance of that model + upstream models was not tested.  
<img width="1115" alt="Screenshot 2024-10-25 at 3 50 57 PM" src="https://github.com/user-attachments/assets/0be4a530-2b67-47d2-84d6-34c88ccd9c74">

Conclusion: Does not appear to have any negative impact on downstream performance making `stg_iterable__user_history` a view. It does save ~16 minutes not having to materialize a table for `stg_iterable__user_history` on ever run.

**Comment by fivetran-reneeli** [comment]
Thanks @justin-fundrise! I'll make this update to the package.
